dist: xenial
language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt

script:
  - flake8 --max-line-length 119 pydataapi
  - mypy --ignore-missing-imports pydataapi
#  - nosetests -v tests
